protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    protected $aboutMenu = array(
        array('label'=>'Biz kimiz?', 'url'=>array('site/bizkimiz')),
        array('label'=>'Amaçlarımız', 'url'=>array('site/amaclar')),
        array('label'=>'Yönetim Kurulumuz', 'url'=>array('site/yonetim_kurulu')),
        array('label'=>'Aktif Üyelerimiz', 'url'=>array('site/aktif_uyeler')),
        array('label'=>'Bize Katılın', 'url'=>array('site/bize_katilin')),
    );
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array (
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xE1E2E3,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
        $etkinlikler = new CActiveDataProvider('Activity',array(
            'criteria' => array(
                'limit' => 4,
                'order' => 'date',
            ),
        ));
        $this->render('index',array('etkinlikler' => $etkinlikler));
	}

	public function actionAmaclar()
	{
        $this->layout='//layouts/aboutpages';
        $this->menu = $this->aboutMenu;
        $this->render('amaclar');
	}

	public function actionBizkimiz()
	{
        $this->layout='//layouts/aboutpages';
        $this->render('bizkimiz');
	}

	public function actionYonetim_kurulu()
	{
        $this->layout='//layouts/aboutpages';
        $this->render('yk');
	}

    public function actionAktif_uyeler()
	{
        $this->layout='//layouts/aboutpages';
        $this->render('activemembers');
	}

    public function actionBize_katilin()
	{
        $this->layout='//layouts/aboutpages';
        $this->render('joinus');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail('tmtowtdio@gmail.com',$model->subject,$model->body,$headers);
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form

        if(Yii::app()->request->isAjaxRequest)
            $this->renderPartial('login',array('model'=>$model));
        else
            $this->render('login',array('model'=>$model));
	}

    public function actionTeamRegister()
    {
		$model=new TeamRegisterForm;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['TeamRegisterForm']))
		{
			$model->attributes=$_POST['TeamRegisterForm'];
			if($model->validate())
            {
                $team = new YarismaTeams;
                $team->attributes = $_POST['TeamRegisterForm'];
                if($team->save())
    				$this->redirect(array('/yarisma'));
                else
                    $model->addErrors($team->errors);
            }
		}

        $this->render('teamregister', array(
                'model'=>$model,
            ));
    }

    public function actionRegister()
    {
		$model=new RegisterForm;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['RegisterForm']))
		{
			$model->attributes=$_POST['RegisterForm'];
			if($model->validate())
            {
                $user = new User;
                $user->attributes = $_POST['RegisterForm'];
                if($user->save())
    				$this->redirect(array('user/view','id'=>$user->id));
                else
                    $model->addErrors($user->errors);
            }
		}

		$this->render('register',array(
			'model'=>$model,
		));
    }

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/layouts/aboutpages.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
    <div class="two-thirds">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
    <div class="one-third">
		<div id="sidebar">
		<?php
			$this->beginWidget('zii.widgets.CPortlet', array(
			));
			$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->aboutMenu,
				'htmlOptions'=>array('class'=>'sideNav'),
			));
			$this->endWidget();
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
    <div class="two-thirds">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
    <div class="one-third">
		<div id="sidebar">
		<?php
			$this->beginWidget('zii.widgets.CPortlet', array(
				'title'=>'Operations',
			));
			$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->menu,
				'htmlOptions'=>array('class'=>'operations'),
			));
			$this->endWidget();
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
	
	<!-- Style sheets -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/reset.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/menu.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/fancybox.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/tooltip.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/default.css" />
	
	<!-- jQuery framework and utilities -->
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery-1.6.4.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery-ui-1.7.2.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.easing.1.3.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/hoverIntent.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.bgiframe.min.js"></script>
	<!-- Drop down menus -->
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/superfish.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/supersubs.min.js"></script>
	<!-- Tooltips -->
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.cluetip.min.js"></script>
	<!-- Input labels -->
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.overlabel.min.js"></script>
	<!-- Anchor tag scrolling effects -->
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.scrollTo-min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.localscroll-min.js"></script>
	<!-- Inline popups/modal windows -->
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.fancybox-1.2.6.pack.js"></script>
	
	<!-- Font replacement (cufón) -->
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/cufon-yui.js" type="text/javascript"></script>
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/LiberationSans.font.js" type="text/javascript"></script>

	<!-- IE only includes (PNG Fix and other things for sucky browsers -->
	
	<!--[if lt IE 7]>
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie-only.css">
		<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/pngFix.min.js"></script>
		<script type="text/javascript"> 
			$(document).ready(function(){ 
				$(document.body).supersleight();
			}); 
		</script> 
	<![endif]-->
	<!--[if IE]><link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie-only-all-versions.css"><![endif]-->

	<!-- Functions to initialize after page load -->
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/onLoad.min.js"></script>

</head>
<body>
<!-- Site Container -->
<div id="Wrapper">
	<div id="PageWrapper">
		<div class="pageTop"></div>
		<div id="Header">
		
			<!-- Main Menu -->
			<div id="MenuWrapper">
				<div id="MainMenu">
					<div id="MmLeft"></div>
					<div id="MmBody">
                        <?php $this->widget('zii.widgets.CMenu',array(
                            'items'=>array(
                            	/*
                                array('label'=>'Anasayfa', 'url'=>array('/site/index')),
                                array('label'=>'Hakkımızda', 'url'=>'#', 'items' =>array(
                                    array('label'=>'Biz kimiz?', 'url'=>array('site/bizkimiz')),
                                    array('label'=>'Amaçlarımız', 'url'=>array('site/amaclar')),
                                    array('label'=>'Yönetim Kurulumuz', 'url'=>array('site/yonetim_kurulu')),
                                    array('label'=>'Aktif Üyelerimiz', 'url'=>array('site/aktif_uyeler')),
                                    array('label'=>'Bize Katılın', 'url'=>array('site/bize_katilin')),
                                )),
                                array('label'=>'Etkinlikler', 'url'=>array('/activity/index')),
                                */
                                array('label'=>'Yarışma', 'url'=>array('/yarisma/')),
                                array('label'=>'Ön Eleme Soruları', 'url'=>array('oneleme/')),
                                /*
                                array('label'=>'News', 'url'=>array('/news'),'visible'=>Yii::app()->user->checkAccess('YeniUye')),
                                array('label'=>'Çalışma Grupları', 'url'=>array('/group/index'), 'items' =>array(
                                    array('label'=>'Algoritma', 'url'=>'#'),
                                    array('label'=>'Dergi', 'url'=>'#'),
                                    array('label'=>'Mobil', 'url'=>'#'),
                                    array('label'=>'Oyun', 'url'=>'#'),
                                    array('label'=>'Web', 'url'=>'#'),
                                    array('label'=>'Yarışma', 'url'=>'#'),
                                )),
                                 */
                                array('label'=>'İletişim', 'url'=>array('/site/contact'),),
                            ),
                            'htmlOptions' => array('class' => 'sf-menu'),
                        )); ?>
                        <div class="mmDivider"></div>				
                        <?php $this->widget('zii.widgets.CMenu',array(
                            'encodeLabel' => false,
                            'items'=>array(
                                /*array('label'=>'<span class="mmLogin">Login</span>', 'url'=>array('/site/login'),'linkOptions'=> array('class'=>'login'),'visible'=> Yii::app()->user->isGuest),
                                array('label'=>'Register', 'url'=>array('/site/register'),'visible'=> Yii::app()->user->isGuest),
                                array('label'=>'<span class="mmLogin">Logout</span>', 'url'=>array('/site/logout'),'linkOptions'=> array('class'=>'logout'),'visible'=> !Yii::app()->user->isGuest),*/
                                array('label'=>'<span class="mmLogin">Takım Giriş</span>', 'url'=>array('/yarisma/login'),'visible'=> Yii::app()->team->isGuest),
                                array('label'=>'Çıkış('.Yii::app()->team->name.')', 'url'=>array('yarisma/logout'),'visible'=> !Yii::app()->team->isGuest),
                            ),
                            'htmlOptions' => array('id'=>'MmOtherLinks', 'class' => 'sf-menu'),
                        )); ?>
                    </div>
                    <div id="MmRight"></div>
                </div>
            </div>
			
			<!-- Search
			<div id="Search">
				<form action="#" id="SearchForm" method="post">
					<p style="margin:0;"><input type="text" name="SearchInput" id="SearchInput" value="" /></p>
					<p style="margin:0;"><input type="submit" name="SearchSubmit" id="SearchSubmit" class="noStyle" value="" /></p>
				</form>
			</div> -->
			
			<!-- Logo -->
			<div id="Logo">
			    <?php echo CHtml::link('','http://cclub.metu.edu.tr/');?>
			</div>
			
			<!-- End of Content -->
			<div class="clear"></div>
		
		</div>

		
		<div class="pageMain">
			<!-- Page Content -->
			<div class="contentArea">
				<?php echo $content; ?>
				<!-- End of Content -->
				<div class="clear"></div>
				
			</div>
			
			<!-- Copyright/legal text -->
			<div id="Copyright">
				<p>
					Copyright &copy; 2012 - cclub - All rights reserved. 
				</p>
			</div>
			
		</div>
</div>

<!-- Activate Font Replacement (cufón) -->
<script type="text/javascript"> Cufon.now(); </script>
<script type="text/javascript">
    Cufon.replace('-3.html');
    $("label.overlabel").overlabel();
    buttonStyles();
    roundCorners();
</script>
</body>

</html>

protected/views/layouts/news.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
    <div class="two-thirds">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
    <div class="one-third">
		<div id="sidebar">
		<?php
            foreach(ChCategory::model()->allWithChannels() as $cat)
            {
			$this->beginWidget('zii.widgets.CPortlet', array(
				'title'=>$cat->name,
			));
			echo '<div class="sideNavWrapper"> <div class="sideNavBox-1"> <div class="sideNavBox-2">';
            $this->widget('zii.widgets.CMenu', array(
                'items'=>$cat->channelList(),
                'htmlOptions'=>array('class'=>'sideNav'),
                'activeCssClass'=>'currentPage',
            ));
            $this->endWidget();
            echo '</div> </div> </div>';
            }
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/yarismapages.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
    <div class="two-thirds">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
    <div class="one-third">
		<div id="sidebar">
		<?php
			$this->beginWidget('zii.widgets.CPortlet', array(
			));
			$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->yarismaMenu,
				'htmlOptions'=>array('class'=>'sideNav'),
			));
			$this->endWidget();
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>