protected/controllers/OnelemeController.php
<?php

class OnelemeController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array (
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xE1E2E3,
			),
		);
	}

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	public function filterAccessControl($filterChain)
	{
	    $filter=new TeamAccessControlFilter;
	    $filter->setRules($this->accessRules());
	    $filter->filter($filterChain);
	}
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'captcha'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create', 'show', 'RequestInput', 'update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	public function actionRequestInput($id)
	{
		$passed = false;
		$model = $this->loadModel($id);
		$rmodel = QuestionResult::model()->findByAttributes(array(
					'team_id' => Yii::app()->team->id,
					'question_id' => $id,
				));
		if(!$rmodel)
		{
			$iomodel = QuestionIo::model()->find(array
				(
					'select' =>'*, rand() as rand',
					'condition' => 'question_id = :qi',
					'limit' => '1',
					'order' => 'rand',
					'params' => array(':qi' => $id),
				));

			$rmodel = new QuestionResult;
			$rmodel->team_id = Yii::app()->team->id;
			$rmodel->question_id = $id;
			$rmodel->input_id = $iomodel->id;
			$rmodel->result = 0;
			$rmodel->request_time = time() + 5 * 60;
			if($rmodel->save())
			{
				$passed = true;
			}
		}
		else
		{
			$passed = true;
			$iomodel = QuestionIo::model()->findByPk($rmodel-> input_id);
		}

		if(!$iomodel)
			throw new CHttpException(404,'The requested page does not exist.');

		if($passed)
		{
			header('Content-Disposition: attachment; filename="input.' . $model->name . '.txt"');	
			header('Content-type: text/plain');
			$fpath = getcwd() . DIRECTORY_SEPARATOR . "inputs" . DIRECTORY_SEPARATOR . 'input-' . $iomodel->id . '.txt';
			if(file_exists($fpath))
				echo file_get_contents($fpath);
			else
				echo $iomodel->input;
			die();
		}
		else
			throw new CHttpException(404,'The requested page does not exist.');

	}

	public function actionShow($id)
	{
        $umodel = new QuestionUploadForm;
		$model = $this->loadModel($id);
		$qmodel = QuestionResult::model()->findByAttributes(array('team_id' => Yii::app()->team->id, 'question_id' => $id));
		$timePassed = $qmodel ? (time() - $qmodel->request_time > 5 * 60) : false;

        if(isset($_POST['QuestionUploadForm']))
		{
            $umodel->attributes=$_POST['QuestionUploadForm'];
            $umodel->outputFile = CUploadedFile::getInstance($umodel,'outputFile');
            $umodel->sourceFile = CUploadedFile::getInstance($umodel,'sourceFile');
            if($umodel->validate())
            {
            	if(!$qmodel || $timePassed)
					throw new CHttpException(404,'The requested page does not exist.');


				if($qmodel->result < 100)
				{
	                $fpath = getcwd() . DIRECTORY_SEPARATOR . "solutions" . DIRECTORY_SEPARATOR . Yii::app()->team->id;
	                if(!file_exists($fpath)) mkdir($fpath);
	                $fpath = $fpath . DIRECTORY_SEPARATOR. $umodel->questionId ;
	                if(!file_exists($fpath)) mkdir($fpath);
	                $fpath = $fpath . DIRECTORY_SEPARATOR;

	                $outputFileName = $fpath . 'output-'.$qmodel->input_id.'.txt';
	                $umodel->outputFile->saveAs($outputFileName);
					$iomodel = QuestionIo::model()->findByAttributes(array('id' => $qmodel->input_id));

					$opath = getcwd() . DIRECTORY_SEPARATOR . "outputs" . DIRECTORY_SEPARATOR . 'output-' . $iomodel->id . '.txt';
					
					if(file_exists($opath))
						$iomodel->output = file_get_contents($opath);

	                $output = file_get_contents($outputFileName);
	                
	                $toreplace = array('\n','\r','\t',' ');
	                $output = str_replace($toreplace, '', $output);
	                $iomodel->output = str_replace($toreplace, '', $iomodel->output);
	                
	                if(md5($output) == md5($iomodel->output))
	                	$qmodel->result = 100;

	                $qmodel->save();

	                $umodel->sourceFile->saveAs($fpath . 'source-'.$qmodel->question_id.'.'. $umodel->sourceFile->getExtensionName());
				}
            }
		}

		$this->render('show',array(
			'model'=>$model,
			'qmodel'=> $qmodel,
			'umodel' => $umodel,
			'timePassed' => $timePassed,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new YarismaQuestion;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['YarismaQuestion']))
		{
			$model->attributes=$_POST['YarismaQuestion'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['YarismaQuestion']))
		{
			$model->attributes=$_POST['YarismaQuestion'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider= YarismaQuestion::model()->findAll();
		$results = QuestionResult::model()->findAll(array('index'=>'question_id','condition' => 'team_id = :ti', 'params' => array(':ti' => Yii::app()->team->id)));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'results' => $results,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new YarismaQuestion('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['YarismaQuestion']))
			$model->attributes=$_GET['YarismaQuestion'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=YarismaQuestion::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='yarisma-question-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/oneleme/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'yarisma-question-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'question'); ?>
		<?php echo $form->textArea($model,'question',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'question'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/oneleme/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'question'); ?>
		<?php echo $form->textArea($model,'question',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/oneleme/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('question')); ?>:</b>
	<?php echo CHtml::encode($data->question); ?>
	<br />


</div>

protected/views/oneleme/admin.php
<?php
$this->breadcrumbs=array(
	'Yarisma Questions'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List YarismaQuestion', 'url'=>array('index')),
	array('label'=>'Create YarismaQuestion', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('yarisma-question-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Yarisma Questions</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'yarisma-question-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'name',
		'question',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/oneleme/create.php
<?php
$this->breadcrumbs=array(
	'Yarisma Questions'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List YarismaQuestion', 'url'=>array('index')),
	array('label'=>'Manage YarismaQuestion', 'url'=>array('admin')),
);
?>

<h1>Create YarismaQuestion</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/oneleme/index.php
<?php
$this->breadcrumbs=array(
	'Yarisma Questions',
);
?>

<h1>Yarisma Sorulari</h1>
<p>Üye olduktan sonra her sorunun altında bir input dosyası indirebilirsiniz. İndirdiğiniz dosyaya ait sonucu yüklemek için 15 dakika zamanınız olacak.
Bu süre içinde doğru cevabı yüklemezseniz bu soru için şansınızı kaybedeceksiniz. Bu yüzden yükleme isteği yapmadan önce programınızın doğru çalıştığından emin olun. </p>
<ul>
<?php 
foreach ($dataProvider as $que) {
	echo "<li>";
	echo CHtml::link($que->name, array('/oneleme/show', 'id' => $que->id));
	if(array_key_exists($que->id, $results) && $results[$que->id]->result > 0)
	{
		echo "[OK]";
	}
	echo "</li>";
}
?>
</ul>

protected/views/oneleme/show.php
<h1><?php echo $model->name; ?></h1>

<?php echo $model->question; ?>


<div>
	<br>
	<br>
</div>
<?php if ($qmodel && $qmodel->result > 0): ?>
	Bu soruyu doğru çözdünüz
<?php elseif ($timePassed): ?>
	<div id="TimePassed">
	Yüklemek için size ayrılan sürenin sonuna geldiniz...
	</div>
<?php else: ?>
	<p><?php echo CHtml::link("İnput indir", array("oneleme/requestInput", 'id' => $model->id)); ?></p>

	<?php if ($qmodel): ?>
		<script type="text/javascript">
			var time = new Date(<?php echo $qmodel->request_time; ?>*1000); 
			var timeToPass = 5 * 60 * 1000;

			console.log(timeToPass);
			$(function()
			{
				var timeRemained;
				function updateTimer() 
				{
					var now = new Date();
					var timeR = (timeToPass - (now - time));
					console.log(timeR);

					timeRemained = timeR > 0 ? new Date(timeR) : new Date(0);
					console.log(timeRemained);
					$('#TimeRemained').html(timeRemained.getMinutes() + ":" + timeRemained.getSeconds());
				}
				setInterval(updateTimer, 1000);
			});
		</script>
		<p><span id="TimeRemained"></span> dakika sonra bu soruya çözüm yükleme hakkını kaybedeceksin</p>

	<?php else: ?>
		İlk defa input indirdikten sonra 5 dk içerisinde output dosyanızı ve kaynak kodunuzu yüklemeniz gerekmektedir<br>
		Kaynak kodunuzu sonradan kopya kontrolü yapmak için istiyoruz.<br>
		Kaynak kodunuz aynı outputu vermezse sorunuz geçersiz sayılacaktır.	<br>
	<?php endif ?>
		Sonuçlar daha sonra kontrol edilecek <br>
<p style="color:#AD245B;">Tabi ki sistem herkes için mukemmel çalışamıyor.. kimsenin mağdur olmaması için cevapları kendimiz de kontrol ediyoruz.. 
	Tek yapmanız gereken soruları çözmek. Doğru cevap olduğundan eminseniz bize ulaşın veya bir sonraki kontrolü bekleyin..</p>
<div id="UploadForm" class="form">

	<?php $form=$this->beginWidget('CActiveForm', array
		(
		'id'=>'media-form',
		'enableAjaxValidation'=>false,
		'htmlOptions'=> array
		(
			'enctype'=>'multipart/form-data',
		),
	)); ?>

<p></p>
	<?php echo $form->errorSummary($umodel); ?>
		<?php echo $form->hiddenField($umodel,'questionId'); ?>
		<table>
		<tr>
		<td width="100">your output file:</td>
		<td><?php echo $form->fileField($umodel,'outputFile'); ?></td>
		<td><?php echo $form->error($umodel,'text'); ?></td>
		</tr>
		<tr>
		<td>your source file:</td>
		<td><?php echo $form->fileField($umodel,'sourceFile'); ?></td>
		<td><?php echo $form->error($umodel,'sourceFile'); ?></td>
		</tr>
		</table>

        <?php if(CCaptcha::checkRequirements()&& Yii::app()->user->isGuest):?>
        <p>
        <?php $this->widget('CCaptcha')?>
        </p>
        <p>
        <?php echo $form->labelEx($umodel, 'verifyCode',array('class'=>'overlabel'))?>
        <?php echo $form->textField($umodel, 'verifyCode',array('class'=>'textInput rounded'))?>
        <?php echo $form->error($umodel, 'verifyCode')?>
        </p>
        <?php endif?>
	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>
<?php $this->endWidget(); ?>
</div><!-- form -->
<?php endif ?>

protected/views/oneleme/update.php
<?php
$this->breadcrumbs=array(
	'Yarisma Questions'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List YarismaQuestion', 'url'=>array('index')),
	array('label'=>'Create YarismaQuestion', 'url'=>array('create')),
	array('label'=>'View YarismaQuestion', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage YarismaQuestion', 'url'=>array('admin')),
);
?>

<h1>Update YarismaQuestion <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/oneleme/view.php
<?php
$this->breadcrumbs=array(
	'Yarisma Questions'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List YarismaQuestion', 'url'=>array('index')),
	array('label'=>'Create YarismaQuestion', 'url'=>array('create')),
	array('label'=>'Update YarismaQuestion', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete YarismaQuestion', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage YarismaQuestion', 'url'=>array('admin')),
);
?>

<h1>View YarismaQuestion #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'question',
	),
)); ?>